/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package repeatme
import java.io.{BufferedWriter, File, FileWriter}
import scala.io.Source
import scala.util.Random

object App {
  def main(args: Array[String]): Unit = {

    val fileName: String = "/Users/thetruongs/IdeaProjects/RepeatMe/app/src/main/resources/Input.txt"
    val sourceFile: Source = Source.fromFile("/Users/thetruongs/IdeaProjects/RepeatMe/app/src/main/resources/Input.txt")
    val sourceFileList: Array[String] = sourceFile.getLines().toArray
    val randomNumberGenerator: Random = new Random
    val randomNumber: Int = randomNumberGenerator.between(1, sourceFileList.length + 1)
    val fileWriter = new BufferedWriter(new FileWriter(new File(fileName), true))
    println(sourceFileList(randomNumber - 1))

    println("Add a new entry by typing here")
    val scanner = scala.io.StdIn.readLine()
    println("\nAdding new entry: " + scanner)
    fileWriter.write("\n" + scanner )
    fileWriter.close()
    sourceFile.close()
  }

  def greeting(): String = "Hello, world!"


}
