/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package repeatme
import scala.io.Source
import scala.util.Random

object App {
  def main(args: Array[String]): Unit = {

    val sourceFile: Source = Source.fromFile("/Users/IdeaProjects/RepeatMe/app/src/main/resources/Input.txt")
    val sourceFileList: Array[String] = sourceFile.getLines().toArray
    val randomNumberGenerator: Random = new Random
    val randomNumber: Int = randomNumberGenerator.between(1, sourceFileList.length + 1)

    println(sourceFileList(randomNumber - 1))

    sourceFile.close()
  }

  def greeting(): String = "Hello, world!"


}
